### ISSUE TITLE
When will the gunns project show you the compilation and installation instructions

### ISSUE THREAD

**Issue by BobCFD** [nasa/gunns#1]
As mentioned in the title, when will the gunns project show you the compilation and installation instructions
and the introduction to the project

**Comment by jasonlharvey** [comment]
This project doesn't have an installation, as it's just source code to be used in models and simulations.  To build sims with GUNNS you need a simulation environment, such as github.com/nasa/trick.  The Wiki has some user's guide information about how to build models and Trick simulations: 

https://github.com/nasa/gunns/wiki/Getting_Started
https://github.com/nasa/gunns/wiki/Intro_Course_Start
https://github.com/nasa/gunns/wiki/Intro_Course_5_1
