### ISSUE TITLE
Add Shailaja Janapati to contributors documentation on wiki.

### ISSUE THREAD

**Issue by nickMAP** [nasa/gunns#70]
Jason,

Stumbled upon this and have been getting crazy nostalgia and good memories. Really awesome to see ya'll have kept up with it and made so many improvements! I was searching for an excuse to make an issue....
You should add Shailaja Janapati in under the "Other Contacts" section on the wiki. She helped me on the eps side with reviewing and writing the links/shapes, gave feedback on the drawings, was a tester for some of the early legacy Gunnshow eps efforts, was an uplifting person to talk to at the end of the day, etc...

Shailaja Janapati (Electrical)

Hope all is well with life and I really hope you and Phillip are rolling in a Titan on EVE by now. =) =)   >.<

Best,
Nick

**Comment by jasonlharvey** [comment]
Hey Nick, it's good to hear from you!  I added Shailaja and a few more that we were missing.  You're always welcome to contribute, Gunnsmith!  One of uuuusssssss.....
Take care,
-J
